### ISSUE TITLE
[bug] sass build error, content appears to be none.

### ISSUE THREAD

**Issue by yzqdev** [sass/dart-sass#1388]
```shell
npm install -g sass
# I have already installed the latest version v1.35.1
```

This is my scss file
```scss
// a.scss
@charset "UTF-8";
.icon-lollipop:before {
  content: '\e6a9';
}
```
It's expected to be:
```css
@charset "UTF-8";
.icon-lollipop:before {
  content: '\e6a9';
}
```
But when i run `sass a.scss b.css` , it turns out to be:
```css
// b.css
@charset "UTF-8";
.icon-lollipop:before {
  content: "";
}
```
So, is this a bug, or i did the wrong thing? 
Thanks.

**Comment by connorskees** [comment]
Hello,

This is intended behavior. I'm not sure of the exact reason why this is intended, but escape sequences in Sass are resolved to the character they represent -- e.g. `\66` becomes `f`. My assumption is that this is done to save on bytes in the output (in this case `\e6a9` should shrink in size when resolved).

Is resolving the escape changing the semantics of your CSS in some way?

**Comment by tidus2102** [comment]
Hi, I got the same issue here:

Sass version: 1.36.0

Source file:
![telegram-cloud-photo-size-5-6053341892579536223-y](https://user-images.githubusercontent.com/7001637/127275259-e80ad262-fdb5-4f79-9dcb-cd60f7c0f979.jpg)

Build with node-sass:
![telegram-cloud-photo-size-5-6053341892579536224-x](https://user-images.githubusercontent.com/7001637/127275328-90e6c83c-7276-4d9b-9f5e-f99ae1e730ed.jpg)

Build with sass:
![telegram-cloud-photo-size-5-6053341892579536225-x](https://user-images.githubusercontent.com/7001637/127275352-04f5ab42-e7d7-42b4-840b-3dcaa7b2b313.jpg)

Please check again!
Thanks

**Comment by connorskees** [comment]
@tidus2102 this is intended behavior. Is this affecting the semantics of your CSS? `node-sass` is deprecated.

Please read the documentation here, https://sass-lang.com/documentation/values/strings#escapes

**Comment by tidus2102** [comment]
@connorskees thanks for your help, I just tried but still get error

scss source:
<img width="292" alt="Screen Shot 2021-07-28 at 14 31 41" src="https://user-images.githubusercontent.com/7001637/127282475-17d88d08-1d0c-432c-ade7-7278a5ba8e26.png">

build with sass:
<img width="283" alt="Screen Shot 2021-07-28 at 14 31 52" src="https://user-images.githubusercontent.com/7001637/127282512-9d3fd788-76f3-4d58-af0c-01b4ce380f61.png">

Have I done something wrong?

**Comment by tidus2102** [comment]
I figured it out

<img width="389" alt="Screen Shot 2021-07-28 at 15 38 05" src="https://user-images.githubusercontent.com/7001637/127291827-fc058f8a-9433-405c-9f53-4201d06e74df.png">

**Comment by stof** [comment]
Well, there should not be any issue. `\e6a9` is a CSS escape sequence representing the U+E6A9 Unicode character. Rendering that unicode character directly is semantically the same in CSS (even though it is not literally the same in the source code). that's what this `` is (as it is a PUA character).

Note that as of dart-sass 1.38, characters from the PUA ranges are rendered as escape sequences in expanded mode (they are still rendered as the Unicode char in compressed mode as that's shorter).

@jathak I suggest closing this issue.

**Comment by creage** [comment]
@stof Such behavior should be configurable I believe. The solution suggested by @tidus2102 works fine so far though.

**Comment by stof** [comment]
@creage the dart-sass output is not configurable, to keep the complexity of the implementation lower.
However, as said above, in dart-sass 1.38+, the expanded mode uses escape sequences to render PUA characters, which makes it easier to work with icon fonts.
